// Word abbreviations — replace common words with shorter forms in narrative text
// Code blocks (between ``` or inline `) are preserved

const ABBREVIATIONS: Record<string, string> = {
  function: "fn",
  functions: "fns",
  configuration: "config",
  configurations: "configs",
  environment: "env",
  environments: "envs",
  variable: "var",
  variables: "vars",
  parameter: "param",
  parameters: "params",
  argument: "arg",
  arguments: "args",
  directory: "dir",
  directories: "dirs",
  information: "info",
  documentation: "docs",
  development: "dev",
  production: "prod",
  implementation: "impl",
  implementations: "impls",
  application: "app",
  applications: "apps",
  database: "db",
  databases: "dbs",
  authentication: "auth",
  authorization: "authz",
  message: "msg",
  messages: "msgs",
  request: "req",
  requests: "reqs",
  response: "res",
  responses: "resps",
  error: "err",
  errors: "errs",
  warning: "warn",
  warnings: "warns",
  successful: "ok",
  successfully: "ok",
  temporary: "tmp",
  package: "pkg",
  packages: "pkgs",
  module: "mod",
  modules: "mods",
  interface: "iface",
  interfaces: "ifaces",
  description: "desc",
  descriptions: "descs",
  reference: "ref",
  references: "refs",
  execute: "exec",
  execution: "exec",
  initialize: "init",
  initialization: "init",
  number: "num",
  numbers: "nums",
  string: "str",
  strings: "strs",
  boolean: "bool",
  object: "obj",
  objects: "objs",
  property: "prop",
  properties: "props",
  attribute: "attr",
  attributes: "attrs",
  element: "el",
  elements: "els",
  component: "comp",
  components: "comps",
  container: "ctr",
  containers: "ctrs",
  controller: "ctrl",
  controllers: "ctrls",
  service: "svc",
  services: "svcs",
  middleware: "mw",
  handler: "hdlr",
  handlers: "hdlrs",
  callback: "cb",
  callbacks: "cbs",
  promise: "prom",
  promises: "proms",
  asynchronous: "async",
  synchronous: "sync",
  declaration: "decl",
  declarations: "decls",
  definition: "def",
  definitions: "defs",
  expression: "expr",
  expressions: "exprs",
  statement: "stmt",
  statements: "stmts",
  condition: "cond",
  conditions: "conds",
  iteration: "iter",
  iterations: "iters",
  recursive: "recur",
  recursion: "recur",
  algorithm: "algo",
  algorithms: "algos",
  optimization: "opt",
  optimizations: "opts",
  performance: "perf",
  infrastructure: "infra",
  architecture: "arch",
  repository: "repo",
  repositories: "repos",
  version: "ver",
  versions: "vers",
  installation: "install",
  dependency: "dep",
  dependencies: "deps",
  extension: "ext",
  extensions: "exts",
  template: "tmpl",
  templates: "tmpls",
  context: "ctx",
  contexts: "ctxs",
  content: "cnt",
  contents: "cnts",
  standard: "std",
  specification: "spec",
  specifications: "specs",
  example: "ex",
  examples: "exs",
  include: "incl",
  includes: "incl",
  including: "incl",
  exclude: "excl",
  excludes: "excl",
  excluding: "excl",
  additional: "addl",
  available: "avail",
  previous: "prev",
  following: "foll",
  current: "curr",
  default: "def",
  defaults: "defs",
  internal: "int",
  external: "ext",
  output: "out",
  outputs: "outs",
  input: "in",
  inputs: "ins",
}

// SessionStart instruction to make model use same abbreviations
const ABBREVIATION_INSTRUCTION = `Use these abbreviations in your responses: ${Object.entries(ABBREVIATIONS).map(([k, v]) => `${k}→${v}`).join(", ")}.`

export function abbreviate(text: string): string {
  // Split by code blocks to preserve them
  const parts = text.split(/(```[\s\S]*?```|`[^`]+`)/g)
  return parts
    .map((part, i) => {
      // Odd indices are code blocks — preserve them
      if (i % 2 === 1) return part
      return applyAbbreviations(part)
    })
    .join("")
}

function applyAbbreviations(text: string): string {
  let result = text
  // Sort by length descending to match longer words first
  const sorted = Object.entries(ABBREVIATIONS).sort((a, b) => b[0].length - a[0].length)
  for (const [full, abbr] of sorted) {
    // Word boundary match, case insensitive
    const regex = new RegExp(`\\b${full}\\b`, "gi")
    result = result.replace(regex, abbr)
  }
  return result
}
